### PR TITLE
#159: Fix menu collapse on scrolling down

### LINKED ISSUE #159: The Navbar Hamburger - Collapses After Scrolling Down the Page
image

Mobile view: 
image

The hamburger seems to be tied to the header when scrolling down.

┆Issue is synchronized with this [Trello card](https://trello.com/c/adjVlhSv) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by cnagadya**
## Motivation
Resolves #159 

## Implementation
Menu remains fixed on large screens when scrolling but is collapsed on smaller screens. 

Also the Navlink component has a couple of unused vars causing linting errors. Momentarily blocking this to enable the commits as shown on  [line 1](https://github.com/cnagadya/covid19/blob/%23159-Fix-Menu-Collapse/client/src/components/NavLink.js#L1). Should all these vars be removed 
i.e [changeLanguage](https://github.com/cnagadya/covid19/blob/%23159-Fix-Menu-Collapse/client/src/components/NavLink.js#L8), [handleChangelanguage](https://github.com/cnagadya/covid19/blob/%23159-Fix-Menu-Collapse/client/src/components/NavLink.js#L59-#L64), [LanguageSelector](https://github.com/cnagadya/covid19/blob/%23159-Fix-Menu-Collapse/client/src/components/NavLink.js#L10) and [mapDispatchToProps](https://github.com/cnagadya/covid19/blob/%23159-Fix-Menu-Collapse/client/src/components/NavLink.js#L172-#L178). The were used in the [currently commented out code block](https://github.com/cnagadya/covid19/blob/%23159-Fix-Menu-Collapse/client/src/components/NavLink.js#L133-#L161)
image

## Screenshots/Links

askco19

### CODE REVIEW

**Comment by aviskarkc10** [comment]
@cnagadya Yes please remove the vars so that linting issues are fixed.

File: client/src/components/NavLink.js [hunk 1]
```diff
@@ -1,10 +1,11 @@
+/* eslint-disable no-unused-vars */
```
Comment (aviskarkc10) [inline client/src/components/NavLink.js:1]: let's remove this and instead fix linting errors

File: client/src/components/NavLink.js [hunk 2]
```diff
@@ -18,14 +19,17 @@ class NavMenu extends Component {
     this.showmenu = this.showmenu.bind(this);
     this.WrapperRef = this.WrapperRef.bind(this);
     this.handleClick = this.handleClick.bind(this);
+    this.hideMenuMobileMenu = this.hideMenuMobileMenu.bind(this);
```
Comment (aviskarkc10) [inline client/src/components/NavLink.js:22]: i think a variable name like `hideMobileMenu` would be more readable?

File: client/src/components/NavLink.js [hunk 3]
```diff
@@ -38,19 +42,24 @@ class NavMenu extends Component {
     });
   }
 
+  hideMenuMobileMenu() {
```
Comment (aviskarkc10) [inline client/src/components/NavLink.js:45]: right now the problem is, the menu is closed whenever we click anywhere outside of the menu. I don't think doing this is a very good solution. And if we were going to go with this solution, using media queries would be a more elegant solution?

File: client/src/components/NavLink.js (hunk 2 above)
Comment (cnagadya) [reply client/src/components/NavLink.js:22]: Ofcourse, that was a naming change from _hideMenuMobile_ > _hideMobileMenu_ gone wrong 😅

File: client/src/components/NavLink.js (hunk 3 above)
Comment (cnagadya) [reply client/src/components/NavLink.js]: askco19
Removed. User now has to click / touch outside for menu to collapse

Comment (aviskarkc10) [reply client/src/components/NavLink.js]: LGTM.
